### ISSUE TITLE
Parity for handling $_SERVER['HTTPS'] = 'on';

### ISSUE THREAD

**Issue by seanosh** [Automattic/vip-container-images#267]
In WPVIP hosted environments, `$_SERVER['HTTPS']` is set to `on` accordingly. In the Lando environment, a condition similar to the following is missing:

```
if ( isset( $_SERVER['HTTP_X_FORWARDED_PROTO'] ) && $_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https' ) {
	$_SERVER['HTTPS'] = 'on';
}
```

This is also pointed out on the WP doc pages for `is_ssl()` [here](https://developer.wordpress.org/reference/functions/is_ssl/). 

If one sets `FORCE_SSL_ADMIN` to `true` in a local environment and without a similar condition to the above that results in  setting of `$_SERVER['HTTPS'] = 'on';`, the result is an endless `HTTP 302` redirect loop.

The fall through condition of checking `'443' == $_SERVER['SERVER_PORT']` also subsequently can't be reached.

Ideally as much of the generated config constants and conditions are incorporated into the local environment one for parity (where it makes sense/is applicable).

**Comment by rinatkhaziev** [comment]
@pschoffer could you take a look, please.

**Comment by pschoffer** [comment]
Hi @seanosh 
sorry for the (super) late response.

Could you please provide steps to reproduce?

We have this filter in place to address just that, but I am not sure if this catches the scenario you are talking about.
https://github.com/Automattic/vip-container-images/blob/master/dev-tools/dev-env-plugin.php#L8

```
add_filter( 'set_url_scheme', function( $url ) {
	$proto = $_SERVER[ 'HTTP_X_FORWARDED_PROTO' ] ?? '';

	if ( 'https' == $proto ) {
		return str_replace( 'http://', 'https://', $url );
	}
	return $url;
});
```

**Comment by seanosh** [comment]
> Could you please provide steps to reproduce?

Pretty sure it'd just be:
1. Add `define( 'FORCE_SSL_ADMIN', true );` to `vip-config.php`
2. Attempt to navigate to `/wp-admin/`

It'd probably be good to do this part:

> Ideally as much of the generated config constants and conditions are incorporated into the local environment one for parity (where it makes sense/is applicable).

e.g. compare a generated `wp-config.php` in a hosted environment against what exists in the local one and ensure it's handled in the right way, at the right time, and in the right order locally as it is in a live/hosted environment.
