### ISSUE TITLE
Question: How do i use `wp-test-runner` image in my current environment

### ISSUE THREAD

**Issue by nprasath002** [Automattic/vip-container-images#62]
I recently tried setting up a local environment using vip cli. Are there any instructions i could follow to set up `wp-test-runner` to run unit tests locally with xdebug enabled?

**Comment by kasparsd** [comment]
It appears that the specific image isn't used [anywhere in the Lando config](https://github.com/Automattic/vip/blob/011dc8e154fd5901277ea038597d30984d1ba731/assets/dev-env.lando.template.yml.ejs) of the `vip` CLI so it probably isn't exposed to the CLI tooling yet. I also don't see [any other command here](https://github.com/Automattic/vip/tree/5d60ef539fb8695093877e96dd57fbbc61db8fa8/src/bin) that would allow running arbitrary commands inside any of the containers.

**Comment by sjinks** [comment]
@nprasath002 you can use a script like this: https://github.com/Automattic/vip-go-mu-plugins/blob/master/bin/test.sh

Just remove [this line](https://github.com/Automattic/vip-go-mu-plugins/blob/master/bin/test.sh#L123) if you need XDebug.
