### ISSUE TITLE
Xdebug is only enabled for FPM SAPI

### ISSUE THREAD

**Issue by svyazy** [Automattic/vip-container-images#716]
Due to using the [-s fpm](https://github.com/Automattic/vip-container-images/blob/master/php-fpm/rootfs/usr/local/bin/run.sh#L5) option, Xdebug is only enabled for the FPM SAPI.
I believe this option needs to be removed to allow debugging of WP CLI commands.

**Comment by sjinks** [comment]
Xdebug used to interfere with the WordPress installer.

I would suggest using `vip dev-env shell --root` and then `phpenmod -s cli xdebug`; will this work for you?

**Comment by svyazy** [comment]
@sjinks Thank you for this nice workaround. It works. But any chance to have this working out of the box?
